### ISSUE TITLE
Blank appointment data validation bug

### ISSUE THREAD

**Issue by vtmeghan** [colinxfleming/dcaf_case_management#808] opened 2017-01-13 00:34 UTC
Had bug where a pledge had been submitted, PT called back for another pregnancy, and somehow the date and clinic had been removed. New date/clinic were not able to be saved because pledge was already marked sent, but pledge was unable to be unsent because date/clinic fields were null.

Colin worked around by unpledging through the backend but actual fix needs to be worked out.

**Comment by colinxfleming** [comment] 2017-01-14 08:16
Steps to recreate:
* create a new patient
* give them an appointment date and clinic name
* submit their pledge
* blank out their appointment date or clinic
* try to save a new appointment date or clinic

Expected behavior: Should save!
Actual behavior: No save!

The pledge sent field validation is tripping us up here. I think in an ideal world it lets you replace but not empty out fields necessary for a pledge after a pledge has been sent, rather than failing to save.

**Comment by valeriecodes** [comment] 2017-01-22 22:32
Takin' a look.

**Comment by valeriecodes** [comment] 2017-01-23 01:04
Hi @colinxfleming !
I don't seem to be able to reproduce this, could you let me know what I'm doing wrong?
Here are the steps I'm taking:
- Going to build your call list & entering a name to get to the create patient screen
- Entering a name, phone number, appointment date (2-1-2017), clinic name and DCAF soft pledge (50) to get a valid record
- Logging a call
- Submitting pledge
- Changing appointment date on page
- Logging another call
- Submitting pledge again
Seems to work as expected. (Appointment date change is reflected.)

**Comment by colinxfleming** [comment] 2017-01-24 05:40
@valeriecodes for the life of me, I can't recreate this either -- when I try and clear out a patient field . Since it's happened all of once to our prod data and we can't recreate, I'm inclined to call this unresolvable as such (or maybe not possible with patients created more recently?) and close.

@vtmeghan can you make sure to flag for the dev team if this pops up again?

**Comment by colinxfleming** [comment] 2017-01-24 23:47
As noted in slack, I think this bug stems from a case of validation rules changing around a little bit in flight, so this will only be an issue in extremely rare cases. Closing as as a wontfix.

**Closed by colinxfleming** 2017-01-24 23:47 UTC
Labels: backend, bug
